interface TestInterface {
    void __test_voidCall();

    void __test_inArg(in int arg);

    void __test_outArg(out int arg);

    void __test_inOutArg(in out int arg);

    void __test_allPrimitiveArgs(byte b, char c, short s, int i, long l, float f, double d, String str);

    int __test_forwardArg(int arg);

    async int __test_forwardArgAsync(int arg);

    [AtLeastOnce]
    void __test_policy_atLeastOnce();
}