SOURCE := ./Rpc/Skeleton.java \
	  ./Rpc/ObjectStreamWriter.java \
	  ./Rpc/InOut.java \
	  ./Rpc/Stub.java \
	  ./Rpc/Callback.java \
	  ./Rpc/ObjectStreamReader.java \
	  ./Rpc/Out.java \
	  ./Rpc/RunningIndex.java \
	  ./Rpc/Compiler/Operation.java \
	  ./Rpc/Compiler/Interface.java \
	  ./Rpc/Compiler/IdlCompiler.java \
	  ./Rpc/Compiler/Emitter.java \
	  ./Rpc/Compiler/Tokenizer.java \
	  ./Rpc/Compiler/IndentedPrintStream.java \
	  ./Rpc/Compiler/ExecutionPolicy.java \
	  ./Rpc/Compiler/JavaStubEmitter.java \
	  ./Rpc/Compiler/JavaInterfaceEmitter.java \
	  ./Rpc/Compiler/IdlEmitter.java \
	  ./Rpc/Compiler/TypeBuilder.java \
	  ./Rpc/Compiler/Parameter.java \
	  ./Rpc/Compiler/JavaSkeletonEmitter.java \
	  ./Rpc/Compiler/Token.java \
	  ./Rpc/Call.java \
	  ./Rpc/Registry/RegistryServer.java \
	  ./Rpc/Registry/ClientHandler.java \
	  ./Rpc/Registry/ServiceInfo.java \
	  ./Rpc/Registry/Registry.java

.PHONY: rpc

rpc:
	javac $(SOURCE)


